config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :tasks do
      delete '/remove', to: 'tasks#remove_image'
    end
  end

  post '/change', to: 'tasks#change_status'
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true
  has_many :tasks, dependent: :destroy

  def incomplete_tasks
    tasks.where(status: 'incomplete')
  end

  def complete_tasks
    tasks.where(status: 'complete')
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "https://pbs.twimg.com/profile_images/378800000543599975/c63a58ff323b22a9e9ad52ffbbfb7f0a.jpeg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :due_date_cannot_be_in_the_past
  belongs_to :list


  def start_date_cannot_be_in_the_past
     if (start_date < Date.today)
       errors.add(:start_date, "can't be in the past")
     end
   end

  def due_date_cannot_be_in_the_past
    if (due_date < Date.today)
      errors.add(:due_date, "can't be in the past")
    end
  end

  def update_status
    if complete?
      update(status: 'incomplete')
    else
      update(status: 'complete')
    end
  end

  def complete?
    status == 'complete'
  end

  def the_past?
    true if self.start_date.present? && self.start_date <= Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :all_lists

  def all_lists
    @lists ||= List.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      flash.now[:error] = @list.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
   @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
     redirect_to root_path
    else
      flash[:error] = @list.errors.full_messages.join(", ")
      render :edit
    end
  end

  def show
    @list = List.find(params[:id])
    @titles = @list.tasks.each {|task| task.title}
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :json

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      new_mailer(@task)
      redirect_to @task.list
    else
      render :new
      flash.now[:error] = @task.errors.full_messages.join(", ")
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      update_mailer(@task)
      redirect_to @task.list
    else
      flash[:error] = @task.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
     @task = Task.find(params[:id])
     list = @task.list
     @task.destroy
     redirect_to list
   end

  def change_status
    task = Task.find(params[:task_id])
    task.status = params[:status]
    if task.save
      respond_with task
    else
      respond_with({errors => task.errors}, :status => 422, :location => "/lists/#{task.list_id}")
    end
  end

  def remove_image
    task = Task.find(params[:task_id])
    list = task.list
    task.image = nil
    task.save!
    redirect_to list
  end

  def new_mailer(task)
    if task.title.include?("/cc")
      split = task.title.split("/cc")
      email = split.last.delete!(" ")
      UserMailer.new_task(email, task).deliver_now
    end
  end

  def update_mailer(task)
    if task.title.include?("/cc")
      split = task.title.split("/cc")
      email = split.last.delete!(" ")
      UserMailer.update_task(email, task).deliver_now
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :body, :start_date, :due_date, :image, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">List.ly</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lists <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% List.all.each do |list| %>
          <li><%= link_to "#{list.title}", list_path(list.id) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>List.ly</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render "layouts/navbar"%>

    <% flash.each do |type, message| %>
      <div class="alert flash <%= type %>">
        <%= message %>
      </div>
    <% end %>

    <h1>Welcome to List.ly</h1>

    <%= yield %>

  </body>
</html>

app/views/lists/_filter.html.erb
<p><button class="sort-by-title">Sort by Title</button></p>

<p><button class="sort-by-due-date">Sort by Due Date</button></p>

<p><input name="name-search" class="name-search" placeholder="Mega Search"></p>

<p><button class="show-all">Show/Hide Complete Tasks</button></p>

<p><button class="show-future">Show Future</button></p>

<p><%= link_to "Add Task", new_list_task_path(@list.id) %></p>

app/views/lists/edit.html.erb
<h1>Edit the List!</h1>
<%= form_for @list do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Edit List" %>
<% end %>

app/views/lists/index.html.erb
<%= link_to "Create New List", new_list_path %>

<% @lists.each do |list| %>
  <div class="list">
    <h3><%= link_to list.title, list_path(list.id) %></h3>
    <p><%= link_to "Edit List", edit_list_path(list.id) %></p>
    <p><%= link_to "Delete List", list_path(list.id), method: :delete %></p>
  </div>
<% end %>

app/views/lists/new.html.erb
<%= form_for @list, url: lists_path do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Create List" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<%= render "lists/filter"%>

<h1>Tasks:</h1>

<div class="each-task">
  <% @list.tasks.each do |task| %>
    <div class="task">
      <% if !task.the_past? %>
        <div class="<%= task.status %>">
          <div class="show-future-tasks">
            <p><%= image_tag task.image.url(:thumb) %></p>
            <p><%= button_to "Remove Image", list_task_remove_path(list_id: task.list_id, task_id: task.id), method: :delete %></button></p>
            <h3>Title: <span class="title"><%= task.title %></span></h3>
            <p>Body: <span class="description"><%= task.body %></span></p>
            <p>Start Date: <span class="start-date"><%= task.start_date %></span></p>
            <p>Due Date: <span class="due-date"><%= task.due_date %></span></p>
            <p><a href="#" class="task-status" data-id=<%=task.id %>><%= task.status %></a></p>
            <p><%= link_to "Edit Task", edit_list_task_path(@list.id, task.id)  %></p>
            <p><%= link_to "Delete Task", list_task_path(@list.id, task.id), method: :delete %></p>
          </div>
        </div>
      <% else  %>
        <div class="<%= task.status %>">
          <p><%= image_tag task.image.url(:thumb) %></p>
          <p><%= button_to "Remove Image", list_task_remove_path(list_id: task.list_id, task_id: task.id), method: :delete %></button></p>
          <h3>Title: <span class="title"><%= task.title %></span></h3>
          <p>Body: <span class="description"><%= task.body %></span></p>
          <p>Start Date: <span class="start-date"><%= task.start_date %></span></p>
          <p>Due Date: <span class="due-date"><%= task.due_date %></span></p>
          <p><a href="#" class="task-status" data-id=<%=task.id %>><%= task.status %></a></p>
          <p><%= link_to "Edit Task", edit_list_task_path(@list.id, task.id)  %></p>
          <p><%= link_to "Delete Task", list_task_path(@list.id, task.id), method: :delete %></p>
        </div>
      <% end  %>
    </div>
  <% end  %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for [@task.list, @task] do |f| %>
  <p><%= f.text_field :title, placeholder: "Title" %><br/>
  <p><%= f.text_area :body, placeholder: "Body" %><br/>
    <p><%= f.label :start_date %>
    <%= f.date_field :start_date %><br/>
  <p><%= f.label :due_date %>
  <%= f.date_field :due_date %><br/>
  <p><%= f.hidden_field :list_id, value: params[:list_id]%>
  <p><%= f.submit "Edit Task" %></p>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>
<%= form_for [:list, @task] do |f| %>
  <p><%= f.text_field :title, placeholder: "Title" %><br/>
  <p><%= f.text_area :body, placeholder: "Body" %><br/>
    <p><%= f.label :start_date %>
    <%= f.date_field :start_date %><br/>
  <p><%= f.label :due_date %>
  <%= f.date_field :due_date %><br/>
  <p><%= f.hidden_field :list_id, value: params[:list_id]%>
  <p><%= f.file_field :image %></p>
  <p><%= f.submit "Create Task" %></p>
<% end %>